// <auto-generated />
using System;
using Macro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Macro.Migrations
{
    [DbContext(typeof(MacroContext))]
    [Migration("20200913042558_SoftwareDate")]
    partial class SoftwareDate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Macro.Models.AdminSettings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaintenanceDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaintenanceTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Scheduled")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("AdminSettings");
                });

            modelBuilder.Entity("Macro.Models.Circuit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CCO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CKT_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DInt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SInt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Circuit");
                });

            modelBuilder.Entity("Macro.Models.DiscoCircuit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CCO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CKT_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DInt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SInt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DiscoCircuits");
                });

            modelBuilder.Entity("Macro.Models.Software", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssignedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurchaseOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoftwareTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SupportExp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Supported")
                        .HasColumnType("bit");

                    b.Property<int>("TotalKeys")
                        .HasColumnType("int");

                    b.Property<int>("UsedKeys")
                        .HasColumnType("int");

                    b.Property<DateTime>("added")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Software");
                });
#pragma warning restore 612, 618
        }
    }
}
